[package]
name = "expensas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", default-features = false, features = ["std"] }
axum = { version = "0.5.7", default-features = false, features = ["http1", "json"] }
sqlx = { version = "0.5.13", default-features = false, features = ["macros", "migrate", "postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.19.2", default-features = false, features = ["io-util", "macros", "rt-multi-thread", "time"] }
